<?php

function map_popup_js_init(){
  $cssPie_path = drupal_get_path('module', 'map_popup_js').'/js/CSSpie.js';
  $js_path = drupal_get_path('module', 'map_popup_js').'/js/popitup.js';
  $js_path2 = drupal_get_path('module', 'map_popup_js').'/js/tabs.js';
  $css_path = drupal_get_path('module', 'map_popup_js').'/css/popup.css';
  $ie_css = drupal_get_path('module', 'map_popup_js').'/css/ie.css';
  drupal_add_css($css_path);
  drupal_add_js($cssPie_path);
  drupal_add_js($js_path);
  drupal_add_js($js_path2);
  drupal_add_css($ie_css, array('group' => CSS_THEME, 'browsers' => array('IE' => 'gte IE 6', '!IE' => FALSE), 'preprocess' => FALSE));
  drupal_add_library('system', 'ui');
}
